# Generated by Django 3.1.7 on 2021-02-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20210222_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='journalM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('centralv', models.CharField(blank=True, max_length=255, null=True)),
                ('branchv', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('vouchertype', models.CharField(blank=True, max_length=255, null=True)),
                ('narration', models.CharField(blank=True, max_length=500, null=True)),
                ('subhed', models.CharField(blank=True, max_length=255, null=True)),
                ('ledjer', models.CharField(blank=True, max_length=255, null=True)),
                ('dabit', models.CharField(blank=True, max_length=255, null=True)),
                ('credit', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
