# Generated by Django 3.1.7 on 2021-02-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_journalm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalm',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
