# Generated by Django 3.1.7 on 2021-02-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20210225_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalm',
            name='credit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalm',
            name='dabit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalm',
            name='ledjer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalm',
            name='subhed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
