# Generated by Django 3.1.7 on 2021-02-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20210225_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalm',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='journalm',
            name='dabit',
        ),
        migrations.RemoveField(
            model_name='journalm',
            name='ledjer',
        ),
        migrations.RemoveField(
            model_name='journalm',
            name='subhed',
        ),
    ]
