# Generated by Django 3.1.7 on 2021-02-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20210225_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledjerm',
            old_name='jvl',
            new_name='jv',
        ),
    ]
