# Generated by Django 3.1.7 on 2021-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20210225_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='subheadm',
            name='credit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subheadm',
            name='dabit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subheadm',
            name='ledjer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
