# Generated by Django 3.1.7 on 2021-02-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20210226_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subheadm',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='subheadm',
            name='dabit',
        ),
        migrations.RemoveField(
            model_name='subheadm',
            name='ledjer',
        ),
    ]
