# Generated by Django 3.1.7 on 2021-03-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20210226_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dabitm',
            name='jv',
        ),
        migrations.RemoveField(
            model_name='ledjerm',
            name='jv',
        ),
        migrations.RemoveField(
            model_name='subheadm',
            name='jv',
        ),
        migrations.AddField(
            model_name='journalm',
            name='Entry_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journalm',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='creditM',
        ),
        migrations.DeleteModel(
            name='dabitM',
        ),
        migrations.DeleteModel(
            name='ledjerM',
        ),
        migrations.DeleteModel(
            name='subheadM',
        ),
    ]
