# Generated by Django 3.1.7 on 2021-03-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_auto_20210308_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='jventrym',
            name='jvdis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.journalm'),
        ),
    ]
