# Generated by Django 3.1.7 on 2021-03-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_jventrym_jvdis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jventrym',
            name='amount',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
