# Generated by Django 3.1.7 on 2021-03-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_auto_20210308_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jventrym',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='jventrym',
            name='entry_type',
        ),
        migrations.CreateModel(
            name='jventrytypeamountM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=300, null=True)),
                ('jvdis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.jventrym')),
            ],
        ),
    ]
