# Generated by Django 3.1.7 on 2021-03-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_auto_20210316_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jventrym',
            name='jvdis',
        ),
        migrations.DeleteModel(
            name='journalM',
        ),
        migrations.DeleteModel(
            name='jventryM',
        ),
    ]
