# Generated by Django 3.1.7 on 2021-03-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_auto_20210318_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinformation',
            name='address',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
