# Generated by Django 3.1.7 on 2021-03-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_auto_20210318_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='producerinformatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, max_length=1500, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
