# Generated by Django 3.1.7 on 2021-03-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_entryinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryinfo',
            name='Client_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.clientinformation'),
        ),
        migrations.AlterField(
            model_name='entryinfo',
            name='Producer_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.producerinformatio'),
        ),
    ]
