# Generated by Django 3.1.7 on 2021-03-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_auto_20210320_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryinfo',
            name='Collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryinfo',
            name='Delivery_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
