# Generated by Django 3.1.7 on 2021-03-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_auto_20210320_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryinfo',
            name='Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryinfo',
            name='Received_Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
