# Generated by Django 3.1.7 on 2021-03-29 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_auto_20210322_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='partmayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('Invoice_date', models.DateField(blank=True, null=True)),
                ('Delivery_Date', models.DateField(blank=True, null=True)),
                ('Collection_date', models.DateField(blank=True, null=True)),
                ('Received_Amount', models.IntegerField(blank=True, default=0, null=True)),
                ('Client_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.clientinformation')),
                ('Producer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.producerinformatio')),
            ],
        ),
    ]
