# Generated by Django 3.1.7 on 2021-03-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_partmayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryinfo',
            name='Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entryinfo',
            name='Received_Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='partmayment',
        ),
    ]
