# Generated by Django 3.1.7 on 2021-04-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_auto_20210329_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryinfo',
            name='Product_return',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
